### ISSUE TITLE
The 'cursor' option is required, except for aggregate with the explain argument.

### ISSUE THREAD

**Issue by VAllens** [sergeyzwezdin/Hangfire.Mongo#102]
`throw MongoDB.Driver.MongoCommandException
  HResult=0x80131500
  Message=Command aggregate failed: The 'cursor' option is required, except for aggregate with the explain argument.
  StackTrace:
   at MongoDB.Driver.Core.WireProtocol.CommandWireProtocol`1.ProcessReply(ConnectionId connectionId, ReplyMessage`1 reply)
   at MongoDB.Driver.Core.WireProtocol.CommandWireProtocol`1.Execute(IConnection connection, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.Server.ServerChannel.ExecuteProtocol[TResult](IWireProtocol`1 protocol, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.Server.ServerChannel.Command[TResult](DatabaseNamespace databaseNamespace, BsonDocument command, IElementNameValidator commandValidator, Func`1 responseHandling, Boolean slaveOk, IBsonSerializer`1 resultSerializer, MessageEncoderSettings messageEncoderSettings, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.CommandOperationBase`1.ExecuteProtocol(IChannelHandle channel, ServerDescription serverDescription, ReadPreference readPreference, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.CommandOperationBase`1.ExecuteProtocol(IChannelSource channelSource, ReadPreference readPreference, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.ReadCommandOperation`1.Execute(IReadBinding binding, CancellationToken cancellationToken)
   at MongoDB.Driver.OperationExecutor.ExecuteReadOperation[TResult](IReadBinding binding, IReadOperation`1 operation, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoDatabaseImpl.ExecuteReadOperation[T](IReadOperation`1 operation, ReadPreference readPreference, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoDatabaseImpl.RunCommand[TResult](Command`1 command, ReadPreference readPreference, CancellationToken cancellationToken)
   at Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategyMigrate.BackupCollection(HangfireDbContext database, String collectionName, MongoSchema currentSchema) in D:\work\MongoDBTest\src\Hangfire.Mongo\src\Hangfire.Mongo\Migration\Strategies\MongoMigrationStrategyMigrate.cs:line 97
   at Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategyMigrate.Migrate(MongoSchema fromSchema, MongoSchema toSchema) in D:\work\MongoDBTest\src\Hangfire.Mongo\src\Hangfire.Mongo\Migration\Strategies\MongoMigrationStrategyMigrate.cs:line 38
   at Hangfire.Mongo.Migration.MongoMigrationManager.Migrate(HangfireDbContext dbContext) in D:\work\MongoDBTest\src\Hangfire.Mongo\src\Hangfire.Mongo\Migration\MongoMigrationManager.cs:line 72
   at Hangfire.Mongo.MongoStorage..ctor(String connectionString, String databaseName, MongoStorageOptions storageOptions) in D:\work\MongoDBTest\src\Hangfire.Mongo\src\Hangfire.Mongo\MongoStorage.cs:line 68
   at Hangfire.Mongo.MongoBootstrapperConfigurationExtensions.UseMongoStorage(IGlobalConfiguration configuration, String connectionString, String databaseName, MongoStorageOptions storageOptions) in D:\work\MongoDBTest\src\Hangfire.Mongo\src\Hangfire.Mongo\MongoBootstrapperConfigurationExtensions.cs:line 115
   at MAS.MASWebCoreModule.<>c__DisplayClass3_0.<PreInitialize>b__0(IAbpHangfireConfiguration configuration) in D:\work\MongoDBTest\src\MAS.Web.Core\MASWebCoreModule.cs:line 64
   at MAS.MASWebCoreModule.PreInitialize() in D:\work\MongoDBTest\src\MAS.Web.Core\MASWebCoreModule.cs:line 62
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Abp.Modules.AbpModuleManager.StartModules()
   at Abp.AbpBootstrapper.Initialize()
`

I'm trying to solve this exception.
I google search other MongoDB components found that have similar problems.
Download your code, breakpoint debugging.
In the BackupCollection method of the MongoMigrationStrategyMigrate class, the last line of code throws an exception.
![image](https://user-images.githubusercontent.com/5094922/30311301-318aa02e-97c7-11e7-9d52-5aa93a2168a1.png)
Add a few lines of code here : 
`{ "cursor", new Dictionary<string, object>
    {
        { "batchSize", 0 }
    }
}`
![image](https://user-images.githubusercontent.com/5094922/30311344-62ae4f2a-97c7-11e7-844e-ab6f6f10ef66.png)
I've successfully eliminated this exception.
I think this cursor is a required option and should be passed in by the developer from the front.
Can you merge the problem in the next version?
Be deeply grateful.

**Comment by MarLoe** [comment]
@VAllens, thank you for your detailed report and preliminary research. I'll take a look at this, and eventually bring it into the next release.
The next release is 0.6.0 and it is coming soon :)

**Comment by VAllens** [comment]
Oh, thanks.
Maybe when, can you tell me?

**Comment by MarLoe** [comment]
@VAllens , We are aiming for end of this week :)

**Comment by MarLoe** [comment]
@VAllens, I just tried with batchSize=0 as you suggested. That has some weird side effects on my machine. It is not really working.
I tried changing it to 1 - and everything works again. Could you try that to see if that fixes you problem or just exposes it again?

**Comment by MarLoe** [comment]
@VAllens, seems batchSize=0 has a special meaning:
https://docs.mongodb.com/manual/reference/method/db.collection.aggregate/#example-aggregate-method-initial-batch-size

> A batchSize of 0 means an empty first batch and is useful for quickly returning a cursor or failure message without doing significant server-side work. Specify subsequent batch sizes to OP_GET_MORE operations as with other MongoDB cursors.

**Comment by VAllens** [comment]
You can use it as a parameter with a default value, let the caller decide whether to change its default value.
In fact, I do not understand the meaning of this parameter, because I do not use this parameter.
Thanks you.

**Comment by VAllens** [comment]
I passed in `batchsize = 0` parameter, just to eliminate the exception.
But I don't know how set the `batchsize` parameter value, just by the default value of the MongoDB official document.

**Comment by MarLoe** [comment]
@VAllens, just change the 0 (zero) in the code you inserted to 1:
`
{
                    "cursor", new Dictionary<string, object>
                    {
                        { "batchSize", 1 }
                    }
                }
`
Please see if that solves your issue.

**Comment by VAllens** [comment]
I've tested both 0 and 1, and I don't see any problems on the surface

**Comment by MarLoe** [comment]
After reading the documentation carefully, I found that "cursor" is no longer optional as of MongoDB 3.4

[MongoDB 3.4 Aggregate](https://docs.mongodb.com/manual/reference/command/aggregate/)
[MongoDB 3.2 Aggregate](https://docs.mongodb.com/v3.2/reference/method/db.collection.aggregate/)

The documentation states that an empty "cursor" element is accepted.

@VAllens, could you please try this out and report back if that solves your issue?
`
{ "cursor", new BsonDocument() }
`

**Comment by MarLoe** [comment]
There is a PR #103 that should solve this problem. Please try it out.

**Comment by VAllens** [comment]
Thank you. I saw these two link documents yesterday.
For this PR [#103](https://github.com/sergeyzwezdin/Hangfire.Mongo/pull/103), I'm test haven't detected any problems. :)

**Comment by MarLoe** [comment]
The fix has been included in the [0.5.3](https://github.com/sergeyzwezdin/Hangfire.Mongo/releases/tag/v0.5.3) release.
It should be available on nuget.org shortly.
