### ISSUE TITLE
DeadLock on concurrent envorinment

### ISSUE THREAD

**Issue by shsouza** [sergeyzwezdin/Hangfire.Mongo#139]
I'm having this issue on production environment with multiple sites hosted in a IIS

Seens that the EventWaitHandle is having trouble to set when multiple threads try to create a new MongoStorage.

```
InnerException : Message : Could not release a lock on the resource 'Migrate': Check inner exception for details.
Source : Hangfire.Mongo
StackTrace :    at Hangfire.Mongo.DistributedLock.MongoDistributedLock.Release()
   at Hangfire.Mongo.DistributedLock.MongoDistributedLock.Dispose()
   at Hangfire.Mongo.Migration.MongoMigrationManager.Migrate(HangfireDbContext dbContext)
   at Hangfire.Mongo.MongoStorage..ctor(String connectionString, String databaseName, MongoStorageOptions storageOptions)
   at ...

InnerException : Message : Access to the path is denied.
Source : mscorlib
StackTrace :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Threading.EventWaitHandle.OpenExistingWorker(String name, EventWaitHandleRights rights, EventWaitHandle& result)
   at Hangfire.Mongo.DistributedLock.MongoDistributedLock.Release()
```

**Comment by gottscj** [comment]
@shsouza,

Sorry for the late reply. We're a bit busy at the moment.

We will take a look asap.

thanks

**Comment by gottscj** [comment]
@shsouza,

Please let us know of 0.5.11 solved your issue.

Thanks!

**Comment by shsouza** [comment]
@gottscj 

After the update no more happened

Thanks

**Comment by gottscj** [comment]
Awesome, thank you for the feedback!
