### ISSUE TITLE
Using Hangfire.Mongo on Cosmos DB with Mongo API enabled

### ISSUE THREAD

**Issue by Vitala** [sergeyzwezdin/Hangfire.Mongo#154]
Is it supposed to work?

I'm currently trying

            var migrationOptions = new MongoMigrationOptions
            {
                Strategy = MongoMigrationStrategy.Drop,
                BackupStrategy = MongoBackupStrategy.None
            };
            var storageOptions = new MongoStorageOptions
            {
                MigrationOptions = migrationOptions
            };

           services.AddHangfire(x => x.UseMongoStorage(connectionString, "jobs", storageOptions));

However I get the exception "MongoCommandException: Command renameCollection failed: Command is not supported.". This is because Cosmos DB in Mongo mode doesn't support renaming collections. But I thought it shouldn't even try renaming in the first place since I stated I don't want any backups and I'm okay with dropping the database.

Without any migration options AddHangfire line just fails with "Hangfire.Mongo version: 0.5.12.0, introduces a new schema version that requires migration." exception.

**Comment by gottscj** [comment]
@Vitala,

Just looking through the code now, I cannot see any apparent path where this can happen. I haven't tried to reproduce it though. Can you confirm this is a problem and maybe provide the details of the exception thrown?

**Comment by Vitala** [comment]
Here is the exception I'm getting

```
Hangfire.Mongo.Migration.MongoMigrationException
  HResult=0x80131500
  Message=Migration failed in Hangfire.Mongo.Migration.Steps.Version07.StateDataRename
  Source=Hangfire.Mongo
  StackTrace:
   at Hangfire.Mongo.Migration.MongoMigrationRunner.Execute(MongoSchema fromSchema, MongoSchema toSchema)
   at Hangfire.Mongo.Migration.MongoMigrationManager.Migrate(HangfireDbContext dbContext)
   at Hangfire.Mongo.MongoStorage..ctor(String connectionString, String databaseName, MongoStorageOptions storageOptions)
   at Hangfire.Mongo.MongoBootstrapperConfigurationExtensions.UseMongoStorage(IGlobalConfiguration configuration, String connectionString, String databaseName, MongoStorageOptions storageOptions)
   at server.Startup.<>c__DisplayClass5_0.<ConfigureServices>b__2(IGlobalConfiguration x) in C:\work\server\Startup.cs:line 151
   at Hangfire.HangfireServiceCollectionExtensions.<>c__DisplayClass0_0.<AddHangfire>b__9(IServiceProvider serviceProvider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Hangfire.HangfireApplicationBuilderExtensions.ThrowIfNotConfigured(IApplicationBuilder app)
   at Hangfire.HangfireApplicationBuilderExtensions.UseHangfireServer(IApplicationBuilder app, BackgroundJobServerOptions options, IEnumerable`1 additionalProcesses, JobStorage storage)
   at server.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IServiceProvider serviceProvider) in C:\work\server\Startup.cs:line 232

Inner Exception 1:
MongoCommandException: Command renameCollection failed: Command is not supported.
  HResult=-2146233088
  Command={{ "renameCollection" : "jobs.hangfire.statedata", "to" : "jobs.hangfire.stateData" }}
  Message=Command renameCollection failed: Command is not supported.
  Source=MongoDB.Driver.Core
  StackTrace:
   at MongoDB.Driver.Core.WireProtocol.CommandUsingQueryMessageWireProtocol`1.ProcessReply(ConnectionId connectionId, ReplyMessage`1 reply)
   at MongoDB.Driver.Core.WireProtocol.CommandUsingQueryMessageWireProtocol`1.Execute(IConnection connection, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.WireProtocol.CommandWireProtocol`1.Execute(IConnection connection, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.Server.ServerChannel.ExecuteProtocol[TResult](IWireProtocol`1 protocol, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.Server.ServerChannel.Command[TResult](ICoreSession session, ReadPreference readPreference, DatabaseNamespace databaseNamespace, BsonDocument command, IEnumerable`1 commandPayloads, IElementNameValidator commandValidator, BsonDocument additionalOptions, Action`1 postWriteAction, CommandResponseHandling responseHandling, IBsonSerializer`1 resultSerializer, MessageEncoderSettings messageEncoderSettings, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.CommandOperationBase`1.ExecuteProtocol(IChannelHandle channel, ICoreSessionHandle session, ReadPreference readPreference, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.CommandOperationBase`1.ExecuteProtocol(IChannelSource channelSource, ICoreSessionHandle session, ReadPreference readPreference, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.WriteCommandOperation`1.Execute(IWriteBinding binding, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.RenameCollectionOperation.Execute(IWriteBinding binding, CancellationToken cancellationToken)
   at MongoDB.Driver.OperationExecutor.ExecuteWriteOperation[TResult](IWriteBinding binding, IWriteOperation`1 operation, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoDatabaseImpl.ExecuteWriteOperation[T](IClientSessionHandle session, IWriteOperation`1 operation, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoDatabaseImpl.RenameCollection(IClientSessionHandle session, String oldName, String newName, RenameCollectionOptions options, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoDatabaseImpl.<>c__DisplayClass33_0.<RenameCollection>b__0(IClientSessionHandle session)
   at MongoDB.Driver.MongoDatabaseImpl.UsingImplicitSession(Action`1 func, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoDatabaseImpl.RenameCollection(String oldName, String newName, RenameCollectionOptions options, CancellationToken cancellationToken)
   at Hangfire.Mongo.Migration.Steps.Version07.StateDataRename.Execute(IMongoDatabase database, MongoStorageOptions storageOptions, IMongoMigrationBag migrationBag)
   at Hangfire.Mongo.Migration.MongoMigrationRunner.Execute(MongoSchema fromSchema, MongoSchema toSchema)
```

Weirdest part here in my opinion is this:   Command={{ "renameCollection" : "jobs.hangfire.statedata", "to" : "jobs.hangfire.stateData" }}

**Comment by langsweirdt** [comment]
I'm running into this issue as well.

However, looking at the code it is quite clear why this happens:

- Selecting MongoMigrationStrategy.None, you end up at this place: https://github.com/sergeyzwezdin/Hangfire.Mongo/blob/0.5.12/src/Hangfire.Mongo/Migration/Strategies/MongoMigrationStrategyNone.cs#L19 which throws an exception and thus not helpful.. 

- Selecting any other MigrationStrategy, you eventually end up executing migration step 7 where a rename operation is preformed: https://github.com/sergeyzwezdin/Hangfire.Mongo/blob/0.5.12/src/Hangfire.Mongo/Migration/Steps/Version07/00_StateDataRename.cs#L35

This is a workaround:

1. use the following settings:

`
var migrationOptions = new MongoMigrationOptions
{
    Strategy = MongoMigrationStrategy.Migrate,
    BackupStrategy = MongoBackupStrategy.None
};
`
2. run your program, the previously mentioned exception is thrown

3. manually delete the collection 'hangfire.statedata' and create a new collection 'hangfire.stateData'

4. in the collection hangfire.schema, delete the document with _id = 6 and create a document with _id = 7

5. run your program again, it will continue with the remaining migrations

An actual fix could be that at this point in the migration: https://github.com/sergeyzwezdin/Hangfire.Mongo/blob/0.5.12/src/Hangfire.Mongo/Migration/Steps/Version07/00_StateDataRename.cs#L35, the exception is caught if it occurs, and if the backup strategy is 'None' collection hangfire.statedata is deleted and hangfire.stateData created. For other  backup strategies, the exception is re-thrown.

**Comment by gottscj** [comment]
@langsweirdt,

thank you for the workaround!

My initial appraoch will be to not use the command "rename", but to do it manually so users with CosmosDB can actually do migrations and backup their data.

**Comment by gottscj** [comment]
@langsweirdt,

We will throw an exception if "MongoMigrationStrategy.None" is choosen and we have changed the schema. The user can then decide how to proceed. 

if the DB is empty we will run all migrations from first schema to last. 
I have changed the migration step to manually copy the data instead of running the "Rename" command.

**Comment by gottscj** [comment]
@langsweirdt,

It should be addressed in 0.5.13.
If you get a chance to check this out please let me know if this works for you so I can close this issue.
Thanks

**Comment by langsweirdt** [comment]
@gottscj Great, I'll verify and let you know.

**Comment by langsweirdt** [comment]
@gottscj I can confirm that 0.5.13 indeed solves this issue. Can be closed.
