### ISSUE TITLE
Job enqueue doesn't support generic methods

### ISSUE THREAD

**Issue by tmm360** [sergeyzwezdin/Hangfire.Mongo#165]
Hangfire should support it on Sql implementation, but generic method parameters are not serialized into the MongoDB document.

Trying to enqueue a call to a generic method I receive `Can not find the target method.`

    Failed
    Can not change the state to 'Processing': target method was not found.

    System.ArgumentNullException
    Value cannot be null.

    System.ArgumentNullException: Value cannot be null.
       at System.Reflection.RuntimeMethodInfo.MakeGenericMethod(Type[] methodInstantiation)
       at Hangfire.Common.TypeExtensions.GetNonOpenMatchingMethod(Type type, String name, Type[] parameterTypes)
       at Hangfire.Storage.InvocationData.Deserialize()

**Comment by gottscj** [comment]
@tmm360,

Doing a small test using the samples, it seems work fine.

Would it be possible for you to write a unit test exposing the behavior?

Thanks

**Comment by tmm360** [comment]
Sure, I will try

**Comment by gottscj** [comment]
@tmm360,

Did you get a chance to test this further? I would be great that, if there is an issue, we could provide a fix for 0.5.14.

Thanks

**Comment by tmm360** [comment]
No I'm sorry, I will try on next days

**Comment by tmm360** [comment]
I didn't write tests, but I wrote very simple cases where this and another (I think very similar and related) issues appear.
On Asp.net Core sample project you can add these lines on `HomeController`:

    public ActionResult FailingOnClient()
    {
        BackgroundJob.Enqueue(() => FailingOnClientJob<string>());
        return RedirectToAction("Index");
    }
        
    public ActionResult FailingOnServer()
    {
        BackgroundJob.Enqueue<FailingOnServerJob>(job => job.Run<string>());
        return RedirectToAction("Index");
    }
        
    public void FailingOnClientJob<T>() { }

    public class FailingOnServerJob
    {
        public void Run<T>() { }
    }

If you invoke the `FailingOnServer` action you will receive the previously mentioned exception by server execution execution, but if you call the `FailingOnClient` action you will get this exception directly on client enqueuing:

	System.ArgumentNullException
	  HResult=0x80004003
	  Message=Value cannot be null.
	  Source=System.Private.CoreLib
	  StackTrace:
	   at System.Reflection.RuntimeMethodInfo.MakeGenericMethod(Type[] methodInstantiation)
	   at Hangfire.Common.TypeExtensions.GetNonOpenMatchingMethod(Type type, String name, Type[] parameterTypes)
	   at Hangfire.Common.Job.FromExpression(LambdaExpression methodCall, Type explicitType)
	   at Hangfire.BackgroundJobClientExtensions.Create(IBackgroundJobClient client, Expression`1 methodCall, IState state)
	   at Hangfire.Mongo.Sample.ASPNetCore.Controllers.HomeController.FailingOnClient() in C:\Users\mirko\Desktop\Hangfire.Mongo\src\Hangfire.Mongo.Sample.ASPNetCore\Controllers\HomeController.cs:line 49
	   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
	   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()

**Comment by gottscj** [comment]
Thanks! I'll try to fix for 0.5.14

**Comment by gottscj** [comment]
@tmm360,

I updated a issue in the Hangfire repo with a failling unit test for this scenario.

https://github.com/HangfireIO/Hangfire/issues/1168

Thanks

**Comment by tmm360** [comment]
Thank you for your help!
You have found my issue, because into my project I don't have a parameter for each generic type that I pass.
I'm using these generic types with an other internal logic, but I've actually solved invoking an other not-generic proxy method that takes these types as arguments, and use reflection for invoke the generic one.

If hangfire could serialize also generic types it would be great!
