### ISSUE TITLE
Jobs fail randomly with System.IO.FileLoadException

### ISSUE THREAD

**Issue by provanguard** [sergeyzwezdin/Hangfire.Mongo#183]
I am getting this error frequently and randomly. I am trying to locate the cause of the problem. Can you help?

```
System.IO.FileLoadException
Could not load file or assembly 'DeploymentCore, Version=1.0.273.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

System.IO.FileLoadException: Could not load file or assembly 'DeploymentCore, Version=1.0.273.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'DeploymentCore, Version=1.0.273.0, Culture=neutral, PublicKeyToken=null'
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type, ObjectHandleOnStack keepalive)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase)
   at Hangfire.Storage.InvocationData.DefaultTypeResolver(String typeName)
   at Hangfire.Storage.InvocationData.Deserialize()
```

I am using MongoDB.Driver version 2.8.0 and have been testing Hangfire versions 1.6.22 - 1.6.25, which all have the issue.

**Comment by provanguard** [comment]
The error went away, after ensuring that only one instance of the application accesses the database. Is this an issue related to the Hangfire.Mongo package, or something specific to the Mongo DB or Hangfire?

**Comment by provanguard** [comment]
Got feedback from Hangfire. It seems to be a Hangfire related problem. They don't support multiple applications or instances of the same application to access the same database.
