### ISSUE TITLE
Error observing notifications

### ISSUE THREAD

**Issue by provanguard** [sergeyzwezdin/Hangfire.Mongo#194]
With the latest Hangfire, Hangfire.Mongo and Mongo, when I use Ctrl+C to stop my dotnet core application running in the debug window, I am getting this exception logged by the application:

```
15:00:18.175|Information|54||Server xxx caught stopped signal...
15:00:18.286|Error|18||Error observing notifications
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at MongoDB.Driver.Core.Connections.BinaryConnection.ReceiveMessageHelper.DecodeMessage(IByteBuffer buffer, IMessageEncoderSelector encoderSelector, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Connections.BinaryConnection.ReceiveMessage(Int32 responseTo, IMessageEncoderSelector encoderSelector, MessageEncoderSettings messageEncoderSettings, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.ConnectionPools.ExclusiveConnectionPool.AcquiredConnection.ReceiveMessage(Int32 responseTo, IMessageEncoderSelector encoderSelector, MessageEncoderSettings messageEncoderSettings, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1.Execute(IConnection connection, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.WireProtocol.CommandWireProtocol`1.Execute(IConnection connection, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.Server.ServerChannel.ExecuteProtocol[TResult](IWireProtocol`1 protocol, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.Server.ServerChannel.Command[TResult](ICoreSession session, ReadPreference readPreference, DatabaseNamespace databaseNamespace, BsonDocument command, IEnumerable`1 commandPayloads, IElementNameValidator commandValidator, BsonDocument additionalOptions, Action`1 postWriteAction, CommandResponseHandling responseHandling, IBsonSerializer`1 resultSerializer, MessageEncoderSettings messageEncoderSettings, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.AsyncCursor`1.ExecuteGetMoreCommand(IChannelHandle channel, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.AsyncCursor`1.GetNextBatch(CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.AsyncCursor`1.MoveNext(CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.AsyncCursorEnumerator`1.MoveNext()
   at Hangfire.Mongo.MongoNotificationObserver.Execute(CancellationToken cancellationToken)
```
Do I need to configure something in order to stop the application "cleanly" ?

**Comment by gottscj** [comment]
@provanguard,

No its expected as cancellation is being requested. I however do not handle it gracefully.

#191 submitted by @LucyGoosey, addresses this issue, I just need to push a new release.

Will do this ASAP.

**Comment by provanguard** [comment]
Thanks for the very quick reply ! I will await the new release.

By the way, I am now working on migration my application from using Hangfire 1.6.x to 1.7.x. Are there any specific actions I should take from the perspective of Hangfire.Mongo and Mongo ?
