### ISSUE TITLE
Operation Cancelled on CheckConnection

### ISSUE THREAD

**Issue by F-Amaral** [sergeyzwezdin/Hangfire.Mongo#195]
Hello, 
So I'm using a remote mongoDB Atlas service to host my mongo cluster, and the connection string is in this format:  

**mongodb+srv://user:pass@cluster-id.mongodb.net/database?retryWrites=true&w=majority.**

I have tried using multiple variations of it within the UseMongoClient method, and it does goes fine up to the CheckConnection method, where it throws a ThrowOperationCancelledException, when reaching this piece of code on the MongoStorage class:

`               try
                {
                    _dbContext.Database.RunCommand((Command<BsonDocument>)"{ping:1}", cancellationToken: cts.Token);
                }
                catch (Exception e)
                {
                    throw new MongoConnectException(_dbContext, CreateObscuredConnectionString(), e);
                }`

The exception message is not very descriptive, just says:

> The operation was canceled.

Here is the exception stack trace: 

`   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at MongoDB.Driver.Core.Clusters.Cluster.WaitForDescriptionChangedHelper.HandleCompletedTask(Task completedTask)
   at MongoDB.Driver.Core.Clusters.Cluster.WaitForDescriptionChanged(IServerSelector selector, ClusterDescription description, Task descriptionChangedTask, TimeSpan timeout, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Clusters.Cluster.SelectServer(IServerSelector selector, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoClient.AreSessionsSupportedAfterServerSelection(CancellationToken cancellationToken)
   at MongoDB.Driver.MongoClient.AreSessionsSupported(CancellationToken cancellationToken)
   at MongoDB.Driver.OperationExecutor.StartImplicitSession(CancellationToken cancellationToken)
   at MongoDB.Driver.MongoDatabaseImpl.UsingImplicitSession[TResult](Func`2 func, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoDatabaseImpl.RunCommand[TResult](Command`1 command, ReadPreference readPreference, CancellationToken cancellationToken)
   at Hangfire.Mongo.MongoStorage.CheckConnection() in D:\Users\Felipe\Documents\Source\Repos\Hangfire.Mongo\src\Hangfire.Mongo\MongoStorage.cs:line 79 `

It'd be awesome if somebody could help shed a light on this. Thank you!

**Comment by uublive** [comment]
We are having the same exact issue as described above, unfortunately also I cannot get more information to share, as the exception doesn't tell much

**Comment by gottscj** [comment]
Hi,

I'm currently on holiday. Did you try to bypass the connection check?

**Comment by uublive** [comment]
hello @gottscj,
by bypassing the check the connection is then ok. I cloned the repo and I'll try to see  what it is about

have good holidays!

**Comment by uublive** [comment]
Ok, it's just the cancellationToken that is too short, as it's set to 1 second. MongoAtlas in some situations can reply to a ping after 1 second, hence the command gets cancelled, throwing the exception 
`MongoConnectException(_dbContext, CreateObscuredConnectionString(), e);` 

On **MongoStorage.cs:75** maybe the timeout for the cancellationToken should be configurable?

**Comment by F-Amaral** [comment]
@uublive Did increasing the timeout solved it for you? For me it didn't matter if it was 1 or 5 or 10, the command still got cancelled in less about 1 second. If I connected to atlas with MongoDB Compass, it connected just fine.

**Comment by uublive** [comment]
Yes, as a test i increased it to 5 seconds and it went through. I'm still keeping the check disabled though.
I think you can safely disabled the check, as it's just a { ping } command anyway


On 16/07/2019 16:10:37, Felipe Amaral <notifications@github.com> wrote:
@uublive [https://github.com/uublive] Did increasing the timeout solved it for you? For me it didn't matter if it was 1 or 5 or 10, the command still got cancelled in less about 1 second. If I connected to atlas with MongoDB Compass, it connected just fine.

**Comment by provanguard** [comment]
Same issue here. I have disabled the ping, for the time being.

**Comment by gottscj** [comment]
@F-Amaral,

I increased the timeout to 5 seconds and made the timeout configurable. 
Please let me konw if this sovles your issue. :)

**Comment by gottscj** [comment]
closing
