### ISSUE TITLE
Cannot work with mongodb.driver 2.9.1

### ISSUE THREAD

**Issue by hetaoos** [sergeyzwezdin/Hangfire.Mongo#203]
Hi, When I upgraded to mongodb.driver 2.9.1, An error is reported when using **Hangfire.RecurringJob.AddOrUpdate**:
```
Method not found:“MongoDB.Bson.BsonDocument MongoDB.Driver.UpdateDefinition`1.Render(MongoDB.Bson.Serialization.IBsonSerializer`1<!0>, MongoDB.Bson.Serialization.IBsonSerializerRegistry)”"

   at Hangfire.Mongo.MongoWriteOnlyTransaction.SerializeWriteModel(WriteModel`1 writeModel)
   at Hangfire.Mongo.MongoWriteOnlyTransaction.Log()
   at Hangfire.Mongo.MongoWriteOnlyTransaction.Commit()
   at Hangfire.RecurringJobManager.AddOrUpdate(String recurringJobId, Job job, String cronExpression, RecurringJobOptions options)
   at Hangfire.RecurringJob.AddOrUpdate(String recurringJobId, Expression`1 methodCall, String cronExpression, TimeZoneInfo timeZone, String queue)
```

Please upgrade the mongodb driver version, thank you.

**Comment by gottscj** [comment]
closing
