### ISSUE TITLE
Capped is set to false when attempting to create collections after being deleted

### ISSUE THREAD

**Issue by Memhave** [sergeyzwezdin/Hangfire.Mongo#204]
Hey,

I've been investigating some issues we've been having at work and one of them is the failure to setup collections if they are deleted or disappear (we have been having issues with queues and a "fix" was to simply delete the mongo storage), but unfortunately the collections arent correctly created after they're gone as you can see:

![good](https://user-images.githubusercontent.com/8819474/64346681-d55a2200-cff2-11e9-9a0d-3b987dba487f.png)

When the service is first brought up, it correctly adds the collections.

![failure](https://user-images.githubusercontent.com/8819474/64346709-e1de7a80-cff2-11e9-8233-16ff81110d90.png)
When the collections are deleted, the collections are not only missing (due to some other issue, not sure) - but capped is set to false which causes about **500,000** errors to be thrown every 30 minutes. 

Here is one time where it successfully created all the necessary tables but capped was still set to true: 

![image](https://user-images.githubusercontent.com/8819474/64356734-a8623b00-d003-11e9-8fb1-b8f8e0901243.png)

**Comment by Memhave** [comment]
As you can see, it throws a lot :D 

![image](https://user-images.githubusercontent.com/8819474/64346875-3d106d00-cff3-11e9-8431-615908cf4e29.png)

**Comment by Memhave** [comment]
I think you're right, that we should never "have" to delete collection but unfortunately we seem to have a use case where:

1) Deploy service + HF to cluster (this is another issue in and of it self it seems, but regardless)
2) Need to deploy due to contract / code changes etc 
3) Need to remove collections in mongo ( + rehydrate other collections) -> easier to simply just drop mongo db itself (to flush the queue if we cant afford to wait for example) 
4) Service (HF) shits itself (regardless if we drop mongo before or after, it will need to be redeployed)

The issue here is that the HF seems to die, spams logs and is generally unrecoverable - we currently use mongo on other services and we seem to have no issue simply dropping the collection (it then recreates it automatically and continues).

I'm not so well versed in mongo (or really HF at this point) - is there some way to set up the driver to be able to recover better?

**Comment by gottscj** [comment]
@Memhave,

I'm not sure I fully understand the need for deleting the "notifications" collection. Do you Delete that collection only? 

MongoDb needs to know if you want to create capped collection, which the "notifications" collection is. If you simply do GetCollection, and the collection has been dropped, it will create a default collection. eg NOT a capped collection. in Hangfire.Mongo we create the in a migration step so if dropped you need to manually tell mongodb that the notifications is capped. We add to the "notifications" collection each time we do queue a job or release a hangfire lock, so its quite frequent.

You can read more on capped collections here.

Would it be possible to simply drop the entire DB instead of collections? then the migrations would run again at startup?
It would be interesting to hear more on why HF service shits itself

more on capped collections
https://docs.mongodb.com/manual/core/capped-collections/

**Comment by Memhave** [comment]
@gottscj 

Thank you for the link, I'll take a read. 

I did try to simply drop the whole DB itself, but the "issue" persists. 

Unfortunately, we've moving away from HF (and "smart" solutions) and simply going without for now, but thank you for your help :).

Feel free to close the issue.

**Comment by hitchhiker** [comment]
Hi @gottscj - thank you for your work. We had a similar problem, and found our server disabled due to 'out of space' on the logging disk. It had written over a terrabyte of log entries!

I believe dropping all HF collections solves it.

> Hangfire.Mongo.MongoNotificationObserver[0]
      Error observing notifications
      MongoDB.Driver.MongoCommandException: Command find failed: error processing query: ns=wom._hangfire.notificationsTree: _id $gt ObjectId('5d555f5df7f761101b95e9ce')
      Sort: {}
      Proj: {}
       tailable cursor requested on non capped collection.
         at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1.ProcessResponse(ConnectionId connectionId, CommandMessage responseMessage)
         at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1.Execute(IConnection connection, CancellationToken cancellationToken)
         at MongoDB.Driver.Core.WireProtocol.CommandWireProtocol`1.Execute(IConnection connection, CancellationToken cancellationToken)
         at MongoDB.Driver.Core.Servers.Server.ServerChannel.ExecuteProtocol[TResult](IWireProtocol`1 protocol, CancellationToken cancellationToken)
         at MongoDB.Driver.Core.Servers.Server.ServerChannel.Command[TResult](ICoreSession session, ReadPreference readPreference, DatabaseNamespace databaseNamespace, BsonDocument command, IEnumerable`1 commandPayloads, IElem
         at MongoDB.Driver.Core.Operations.CommandOperationBase`1.ExecuteProtocol(IChannelHandle channel, ICoreSessionHandle session, ReadPreference readPreference, CancellationToken cancellationToken)
         at MongoDB.Driver.Core.Operations.CommandOperationBase`1.ExecuteProtocol(IChannelSource channelSource, ICoreSessionHandle session, ReadPreference readPreference, CancellationToken cancellationToken)
         at MongoDB.Driver.Core.Operations.ReadCommandOperation`1.Execute(IReadBinding binding, CancellationToken cancellationToken)
         at MongoDB.Driver.Core.Operations.FindCommandOperation`1.Execute(IReadBinding binding, CancellationToken cancellationToken)
         at MongoDB.Driver.Core.Operations.FindOperation`1.Execute(IReadBinding binding, CancellationToken cancellationToken)
         at MongoDB.Driver.OperationExecutor.ExecuteReadOperation[TResult](IReadBinding binding, IReadOperation`1 operation, CancellationToken cancellationToken)
         at MongoDB.Driver.MongoCollectionImpl`1.ExecuteReadOperation[TResult](IClientSessionHandle session, IReadOperation`1 operation, ReadPreference readPreference, CancellationToken cancellationToken)
         at MongoDB.Driver.MongoCollectionImpl`1.ExecuteReadOperation[TResult](IClientSessionHandle session, IReadOperation`1 operation, CancellationToken cancellationToken)
         at MongoDB.Driver.MongoCollectionImpl`1.FindSync[TProjection](IClientSessionHandle session, FilterDefinition`1 filter, FindOptions`2 options, CancellationToken cancellationToken)
         at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSession[TResult](Func`2 func, CancellationToken cancellationToken)
         at MongoDB.Driver.MongoCollectionImpl`1.FindSync[TProjection](FilterDefinition`1 filter, FindOptions`2 options, CancellationToken cancellationToken)
         at Hangfire.Mongo.MongoNotificationObserver.Execute(CancellationToken cancellationToken)
fail: Hangfire.Mongo.MongoNotificationObserver[0]
      Error observing notifications

**Comment by gottscj** [comment]
@hitchhiker,
yikes. I will make a patch so that if the notifications observer fails with "NotCapped" failure. I will not try to read from that collection again. If the observer is not running, Hangfire.Mongo will behave like the previous versions where we poll for locks and queued jobs. I will add a error log entry though.

**Comment by gottscj** [comment]
I added #215. If Hangfire.Mongo gets an MongoCommandError (if not capped), it will not try to restart the observer.

It will report an (one) error and stop. documents inserted into the notifications collection will not be cleaned up and Hangfire.Mongo will fallback to rely on polling for queued jobs and released locks.

**Comment by gottscj** [comment]
closing
