### ISSUE TITLE
Execution of RecurringJob is failed because of Azure CosmoDB (MongoDB) error : E11000 duplicate key error collection: Schedule.hangfire.jobGraph Failed _id or unique key constraint

### ISSUE THREAD

**Issue by anton-tsiatsko** [sergeyzwezdin/Hangfire.Mongo#205]
1) DB = Azure CosmoDB (Mongo API)
2) .Net Core 2.2
3) Configuration:
            services.AddHangfire(configuration => configuration
                .SetDataCompatibilityLevel(CompatibilityLevel.Version_170)
                .UseSimpleAssemblyNameTypeSerializer()
                .UseRecommendedSerializerSettings()
                .UseMongoStorage(MongoClientSettings.FromConnectionString(dbSettings.ConnectionString), dbSettings.DatabaseName, 
                                    new MongoStorageOptions { CheckConnection = false,
                                                          MigrationOptions = new MongoMigrationOptions
                                                            { Strategy = MongoMigrationStrategy.Migrate, BackupStrategy = MongoBackupStrategy.Collections } }));
            services.AddHangfireServer();
4) PackageReference Include="Hangfire.Core" Version="1.7.1"
    PackageReference Include="Hangfire.AspNetCore" Version="1.7.1"
    PackageReference Include="HangFire.Mongo" Version="0.6.3"
    PackageReference Include="Microsoft.AspNetCore.App"
    PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.2.0" PrivateAssets="All"
    PackageReference Include="MongoDB.Driver" Version="2.9.1"

5) Code works ok with Desktop MongoDB 

Code:
`            RecurringJob.AddOrUpdate(() => Log.Error("Recurring!"),Cron.MinuteInterval(1));
`

Log1 :
09-18-2019 00:12:08.123 [ WRN ] PRIMARYPC Hangfire.Server.RecurringJobScheduler: Recurring job 'Log.Error' can not be scheduled due to an exception.
MongoDB.Driver.MongoBulkWriteException1[MongoDB.Bson.BsonDocument]: A bulk write operation resulted in one or more errors.
  E11000 duplicate key error collection: Schedule.hangfire.jobGraph Failed _id or unique key constraint
   at MongoDB.Driver.MongoCollectionImpl1.BulkWrite(IClientSessionHandle session, IEnumerable1 requests, BulkWriteOptions options, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl1.<>c__DisplayClass23_0.<BulkWrite>b__0(IClientSessionHandle session)
   at MongoDB.Driver.MongoCollectionImpl1.UsingImplicitSession[TResult](Func2 func, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl1.BulkWrite(IEnumerable1 requests, BulkWriteOptions options, CancellationToken cancellationToken)
   at Hangfire.Mongo.MongoWriteOnlyTransaction.Commit()
   at Hangfire.Server.RecurringJobScheduler.EnqueueBackgroundJob(BackgroundProcessContext context, IStorageConnection connection, String recurringJobId, DateTime now)
   at Hangfire.Server.RecurringJobScheduler.TryEnqueueBackgroundJob(BackgroundProcessContext context, IStorageConnection connection, String recurringJobId, DateTime now)
09-18-2019 00:12:11.115 [ WRN ] PRIMARYPC Hangfire.Server.RecurringJobScheduler: Recurring job 'Log.Error' can not be scheduled due to an exception.
MongoDB.Driver.MongoBulkWriteException1[MongoDB.Bson.BsonDocument]: A bulk write operation resulted in one or more errors.
  E11000 duplicate key error collection: Schedule.hangfire.jobGraph Failed _id or unique key constraint
   at MongoDB.Driver.MongoCollectionImpl1.BulkWrite(IClientSessionHandle session, IEnumerable1 requests, BulkWriteOptions options, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl1.<>c__DisplayClass23_0.<BulkWrite>b__0(IClientSessionHandle session)
   at MongoDB.Driver.MongoCollectionImpl1.UsingImplicitSession[TResult](Func2 func, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl1.BulkWrite(IEnumerable1 requests, BulkWriteOptions options, CancellationToken cancellationToken)
   at Hangfire.Mongo.MongoWriteOnlyTransaction.Commit()
   at Hangfire.Mongo.MongoConnection.CreateExpiredJob(Job job, IDictionary2 parameters, DateTime createdAt, TimeSpan expireIn)
   at Hangfire.Client.CoreBackgroundJobFactory.Create(CreateContext context)
   at Hangfire.Client.BackgroundJobFactory.<>c__DisplayClass9_0.<CreateWithFilters>b__0()
   at Hangfire.Client.BackgroundJobFactory.InvokeClientFilter(IClientFilter filter, CreatingContext preContext, Func1 continuation)
   at Hangfire.Client.BackgroundJobFactory.Create(CreateContext context)
   at Hangfire.RecurringJobExtensions.TriggerRecurringJob(IBackgroundJobFactory factory, JobStorage storage, IStorageConnection connection, IProfiler profiler, RecurringJobEntity recurringJob, DateTime now)
   at Hangfire.Server.RecurringJobScheduler.EnqueueBackgroundJob(BackgroundProcessContext context, IStorageConnection connection, String recurringJobId, DateTime now)
   at Hangfire.Server.RecurringJobScheduler.TryEnqueueBackgroundJob(BackgroundProcessContext context, IStorageConnection connection, String recurringJobId, DateTime now)

Log2:
MongoDB.Driver.MongoBulkWriteException1[MongoDB.Bson.BsonDocument]: A bulk write operation resulted in one or more errors.
  E11000 duplicate key error collection: Schedule.hangfire.jobGraph Failed _id or unique key constraint
   at MongoDB.Driver.MongoCollectionImpl1.BulkWrite(IClientSessionHandle session, IEnumerable1 requests, BulkWriteOptions options, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl1.<>c__DisplayClass23_0.<BulkWrite>b__0(IClientSessionHandle session)
   at MongoDB.Driver.MongoCollectionImpl1.UsingImplicitSession[TResult](Func2 func, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl1.BulkWrite(IEnumerable1 requests, BulkWriteOptions options, CancellationToken cancellationToken)
   at Hangfire.Mongo.MongoWriteOnlyTransaction.Commit()
   at Hangfire.Server.RecurringJobScheduler.EnqueueBackgroundJob(BackgroundProcessContext context, IStorageConnection connection, String recurringJobId, DateTime now)
   at Hangfire.Server.RecurringJobScheduler.TryEnqueueBackgroundJob(BackgroundProcessContext context, IStorageConnection connection, String recurringJobId, DateTime now)

[hangfire.jobGraph.5d814c0a5aca1b15b0b41540.txt](https://github.com/sergeyzwezdin/Hangfire.Mongo/files/3623501/hangfire.jobGraph.5d814c0a5aca1b15b0b41540.txt)
[hangfire.jobGraph.5d814c26a1b5bd22d88cb203.txt](https://github.com/sergeyzwezdin/Hangfire.Mongo/files/3623502/hangfire.jobGraph.5d814c26a1b5bd22d88cb203.txt)
[hangfire.jobGraph.5d814c0a5aca1b15b0b4153f.txt](https://github.com/sergeyzwezdin/Hangfire.Mongo/files/3623503/hangfire.jobGraph.5d814c0a5aca1b15b0b4153f.txt)

**Comment by gottscj** [comment]
@anton-tsiatsko,

I would love to support CosmosDB using the MongoDB.Driver, but there are simply too many things CosmosDB does not support compared to MongoDB, so I had to give it up.

Did you try https://github.com/imranmomin/Hangfire.AzureDocumentDB

Else let me know. I might get bandwidth to create a new repo specific for CosmosDB

**Comment by anton-tsiatsko** [comment]
@gottscj  Thank you for your comment. I'll go with Hangfire.AzureDocumentDB

**Comment by PandaxZA** [comment]
> @anton-tsiatsko,
> 
> I would love to support CosmosDB using the MongoDB.Driver, but there are simply too many things CosmosDB does not support compared to MongoDB, so I had to give it up.
> 
> Did you try https://github.com/imranmomin/Hangfire.AzureDocumentDB
> 
> Else let me know. I might get bandwidth to create a new repo specific for CosmosDB

@gottscj 
Just checking if there is any ideas on bandwidth for this? Would be hugely appreciated

**Comment by dreschner** [comment]
@gottscj 
I would also appreciate a version which supports the MongoDB API of CosmosDB. It workes great for us until version 0.5.12 on which we're stuck now. Everything above has problems with migrating the database schema to version 09 (using of capped collections which are not supported) as well as the problems described by @anton-tsiatsko .

Using Hangfire.AzureDocumentDB or Hangfire.AzureCosmosDB isn't an alternative as it needs an cosmos db instance with SQL API instead of MongoDB API.

**Comment by gottscj** [comment]
@dreschner,

I simply dont have the bandwidth at this moment to support Cosmos also. I do have it in the pipeline though.

Every class in the Hangfire.Mongo driver is overridable though. following the steps below, you should be able to support Cosmos in your setup by overriding existing classes:
I would love a PR, but a requirement is that none of the existing code is touched, which should be possible.

1. Create new CosmosStorage inheriting from MongoStorage.
2. override "GetComponents" only return "yield return StorageOptions.Factory.CreateMongoExpirationManager(HangfireDbContext, StorageOptions);" dont return NotificationObserver. it expects a capped collection.
3. Create new CosmosMigrationFactory. override "GetOrderedMigrations", write new migrations specific for cosmos db and inject them into the list, remove unwanted ones.
4. in your "CosmosStorageOptions" you need to override the default MongoMigrationOptions. Perhaps even create a CosmosMigrationOptions class.
5. Create a CosmosFactory inheriting the MongoFactory. override "CreateMongoJobFetcher", with a new class with the needed changes.

**Comment by HR-de** [comment]
Is the support for cosmos db in place?

**Comment by gottscj** [comment]
@HR-de,

No, not yet. for now you can do the above steps to support Cosmos. It is on the list though

thanks

**Comment by HR-de** [comment]
Hi Jonas,

I am new to both cosmos mongo and hangfire as well. So I am not sure what
are the implementaions to be given for the steps you are referring to.
Any guidance would be greatly appreciated.

Thanks

**Comment by zahichemaly** [comment]
I managed to solve it by deleting the unique index "Key" in the "hangfire.mongo.jobGraph" collection. 

The collection and indexes were being created automatically the first time you schedule a job, and upon comparing the collection on a native Mongo db, I noticed that the index "Key" being created is both unique and sparse, and Cosmos does not support sparse indexes, so it was creating the index as just unique.

**Comment by dragouf** [comment]
> I managed to solve it by deleting the unique index "Key" in the "hangfire.mongo.jobGraph" collection.

@zahichemaly how did you managed to do that ?
