### ISSUE TITLE
Error observing notifications (tailable cursor requested on non capped collection)

### ISSUE THREAD

**Issue by lfongaroScp** [sergeyzwezdin/Hangfire.Mongo#207]
Hi,
I use Hangifire with Mongo Db and Net Core 2.2
Every nuget packages are update to the last stable version 
(Hangfire.AspNetCore, Hangfire.Core, Hangfire.Mongo, Hangifire.Console)

I use hangire.mongo without problems for several months, but today on my test server I get these exceptions:

```
Error observing notifications
MongoDB.Driver.MongoCommandException: Command find failed: error processing query: ns=AcmeCatalog.hf.notificationsTree: _id $gt ObjectId('5d820f5ea892401744c44b56')
Sort: {}
Proj: {}
 tailable cursor requested on non capped collection.
   at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1.ProcessResponse(ConnectionId connectionId, CommandMessage responseMessage)
   at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1.Execute(IConnection connection, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.WireProtocol.CommandWireProtocol`1.Execute(IConnection connection, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.Server.ServerChannel.ExecuteProtocol[TResult](IWireProtocol`1 protocol, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.Server.ServerChannel.Command[TResult](ICoreSession session, ReadPreference readPreference, DatabaseNamespace databaseNamespace, BsonDocument command, IEnumerable`1 commandPayloads, IElementNameValidator commandValidator, BsonDocument additionalOptions, Action`1 postWriteAction, CommandResponseHandling responseHandling, IBsonSerializer`1 resultSerializer, MessageEncoderSettings messageEncoderSettings, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.CommandOperationBase`1.ExecuteProtocol(IChannelHandle channel, ICoreSessionHandle session, ReadPreference readPreference, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.ReadCommandOperation`1.ExecuteAttempt(RetryableReadContext context, Int32 attempt, Nullable`1 transactionNumber, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.RetryableReadOperationExecutor.Execute[TResult](IRetryableReadOperation`1 operation, RetryableReadContext context, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.ReadCommandOperation`1.Execute(RetryableReadContext context, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.FindCommandOperation`1.Execute(RetryableReadContext context, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.FindOperation`1.Execute(RetryableReadContext context, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.FindOperation`1.Execute(IReadBinding binding, CancellationToken cancellationToken)
   at MongoDB.Driver.OperationExecutor.ExecuteReadOperation[TResult](IReadBinding binding, IReadOperation`1 operation, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.ExecuteReadOperation[TResult](IClientSessionHandle session, IReadOperation`1 operation, ReadPreference readPreference, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.ExecuteReadOperation[TResult](IClientSessionHandle session, IReadOperation`1 operation, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.FindSync[TProjection](IClientSessionHandle session, FilterDefinition`1 filter, FindOptions`2 options, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.<>c__DisplayClass41_0`1.<FindSync>b__0(IClientSessionHandle session)
   at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSession[TResult](Func`2 func, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.FindSync[TProjection](FilterDefinition`1 filter, FindOptions`2 options, CancellationToken cancellationToken)
   at Hangfire.Mongo.MongoNotificationObserver.Execute(CancellationToken cancellationToken)
```

about 30k of this kind of exceptions in about 3 hours, change only the id of the query.
I do not modify the hangfire configuration nor the database configuration, I deploy a new version of my dot.Net application.
No error in Hangfire console and no failed jobs.

Any ideas?

**Comment by gottscj** [comment]
@lfongaroScp,

Did you by any chance delete the notifications collection? the error message:
"tailable cursor requested on non capped collection" tells me that the notifications collection which we use to signal queued jobs and released locks, is no longer "capped", which it should be.

Could you elaborate a bit on the how this happened?

thanks!

**Comment by lfongaroScp** [comment]
Hi,


> Did you by any chance delete the notifications collection?

The collection is still there (I check it). I manually execute the query and It execute succefully. 

> Could you elaborate a bit on the how this happened?

Thanks for the reply. My application use NetCore 2.2 for the server side and angular for the client side. MongoDb as database (I use the c# driver to manipulate it).
Before the last deploy everything seems work fine. I modify only a couple of angular files (I double check the commit, only *.ts and *.html files) and deploy the new version through Visual Studio 2019.
After a couple of minutes I start to see the exceptions.

**Comment by gottscj** [comment]
Could you verify the collection <prefix>.notifications is infact a capped collection?

you can either use tools like Studio 3T or the mongo shell
https://docs.mongodb.com/manual/core/capped-collections/

**Comment by lfongaroScp** [comment]
Hi,
It is _not_ capped :-O 

In production server it is capped, but _not_ in the test server. The database in test server is a copy of the database in the online server, so I don't know why there is this difference.
Anyway it's not a problem of the library.

Thanks for the help!
