### ISSUE TITLE
Race Condition in MigrationLock

### ISSUE THREAD

**Issue by jondavidford** [sergeyzwezdin/Hangfire.Mongo#208]
Hi there!

Somewhat related to this PR https://github.com/sergeyzwezdin/Hangfire.Mongo/pull/166, I've found another race condition that exists related to locks.

~~Since a different collection is used for MigrationLocks, that unique index that was added in https://github.com/sergeyzwezdin/Hangfire.Mongo/pull/166 does not apply and hence no guarantee that the mongo upsert will not insert two locks simultaneously. See https://docs.mongodb.com/manual/reference/method/db.collection.update/#use-unique-indexes for more information.~~

~~What ends up happening is that multiple migrations can be run at once, resulting in migration failure. Even when using MigrationStrategy.Drop since a migration is still run under that strategy.~~

~~Would recommend that the migration locks use the same collection as the distributed locks to reuse the index there, but could add another index to the current migration lock collection if preferred.~~

Looks like my original theory on this was incorrect since the migration lock is using _id which should be uniquely indexed.

**Comment by gottscj** [comment]
@jondavidford,

Thanks for your input. I use a different approach on the MigrationLock. I use a static Id which all locks share to try to acquire the lock.

Would you agree that this would ensure an atomic operation?

```csharp
private readonly BsonDocument _migrationIdFilter =
            new BsonDocument("_id", new BsonObjectId("5c351d07197a9bcdba4832fc"));
var update = Builders<MigrationLockDto>
                        .Update
                        .SetOnInsert(_ => _.ExpireAt, lockTimeoutTime);
                    
                    var options = new FindOneAndUpdateOptions<MigrationLockDto>
                    {
                        IsUpsert = true,
                        ReturnDocument = ReturnDocument.Before
                    };

                      var result = _migrationLock.FindOneAndUpdate(_migrationIdFilter, update, options);
```

**Comment by jondavidford** [comment]
Ah, I didn't notice that when reading the code. It would seem that an atomic operation is guaranteed there since the _id should be uniquely indexed. 

But based on my observations I believe that somehow multiple migrations are able to run simultaneously. The below stack trace is an example of an error we are seeing happen occasionally when using migration strategy drop. Wondering if you have any other ideas on how that might be possible? Perhaps too short of a migration timeout...? But don't see how it should take longer than 30 seconds when using migration strategy drop.

```Unhandled Exception: System.AggregateException: One or more errors occurred. (Migration failed in Hangfire.Mongo.Migration.Steps.Version17.AddNotificationsCollection) ---> Hangfire.Mongo.Migration.MongoMigrationException: Migration failed in Hangfire.Mongo.Migration.Steps.Version17.AddNotificationsCollection ---> MongoDB.Driver.MongoCommandException: Command create failed: a collection 'Swimlane.hangfire.notifications' already exists.
   at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1.ProcessResponse(ConnectionId connectionId, CommandMessage responseMessage)
   at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1.Execute(IConnection connection, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.WireProtocol.CommandWireProtocol`1.Execute(IConnection connection, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.Server.ServerChannel.ExecuteProtocol[TResult](IWireProtocol`1 protocol, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.Server.ServerChannel.Command[TResult](ICoreSession session, ReadPreference readPreference, DatabaseNamespace databaseNamespace, BsonDocument command, IEnumerable`1 commandPayloads, IElementNameValidator commandValidator, BsonDocument additionalOptions, Action`1 postWriteAction, CommandResponseHandling responseHandling, IBsonSerializer`1 resultSerializer, MessageEncoderSettings messageEncoderSettings, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.CommandOperationBase`1.ExecuteProtocol(IChannelHandle channel, ICoreSessionHandle session, ReadPreference readPreference, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.CommandOperationBase`1.ExecuteProtocol(IChannelSource channelSource, ICoreSessionHandle session, ReadPreference readPreference, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.WriteCommandOperation`1.Execute(IWriteBinding binding, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.CreateCollectionOperation.Execute(IWriteBinding binding, CancellationToken cancellationToken)
   at MongoDB.Driver.OperationExecutor.ExecuteWriteOperation[TResult](IWriteBinding binding, IWriteOperation`1 operation, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoDatabaseImpl.ExecuteWriteOperation[T](IClientSessionHandle session, IWriteOperation`1 operation, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoDatabaseImpl.CreateCollectionHelper[TDocument](IClientSessionHandle session, String name, CreateCollectionOptions`1 options, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoDatabaseImpl.CreateCollection(IClientSessionHandle session, String name, CreateCollectionOptions options, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoDatabaseImpl.UsingImplicitSession(Action`1 func, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoDatabaseImpl.CreateCollection(String name, CreateCollectionOptions options, CancellationToken cancellationToken)
   at Hangfire.Mongo.Migration.Steps.Version17.AddNotificationsCollection.Execute(IMongoDatabase database, MongoStorageOptions storageOptions, IMongoMigrationContext migrationContext)
   at Hangfire.Mongo.Migration.MongoMigrationRunner.Execute(MongoSchema fromSchema, MongoSchema toSchema)
   --- End of inner exception stack trace ---
   at Hangfire.Mongo.Migration.MongoMigrationRunner.Execute(MongoSchema fromSchema, MongoSchema toSchema)
   at Hangfire.Mongo.Migration.MongoMigrationManager.Migrate()
   at Hangfire.Mongo.Migration.MongoMigrationManager.MigrateIfNeeded(MongoStorageOptions storageOptions, IMongoDatabase database)
   at Hangfire.Mongo.MongoStorage..ctor(MongoClientSettings mongoClientSettings, String databaseName, MongoStorageOptions storageOptions)```

**Comment by gottscj** [comment]
@jondavidford,

Thanks. I'll take a look!

**Comment by gottscj** [comment]
@jondavidford,

Would you be able to reproduce this while enabling logging? you should enable verbosity level INFO.

Thanks!

**Comment by gottscj** [comment]
@jondavidford,

I havent been able to reproduce, but in principle there should be small window as I try to delete the lock object when hangfire is starting up. this could potentially create a window. I addressed it in the referenced link.

**Comment by jondavidford** [comment]
Thanks @gottscj, I have not had much luck reproducing this on my end either. That looks promising as a fix. Let's close the issue and I will reopen if I am able to reproduce and provide more evidence.
