### ISSUE TITLE
Wirte hangfire.jobGraph  error   Key dup key

### ISSUE THREAD

**Issue by cnkker** [sergeyzwezdin/Hangfire.Mongo#229]
2020-03-12 11:40:18 [DEBUG] (Hangfire.Server.Worker) State change attempt 1 of 10 failed due to an error, see inner exception for details
MongoDB.Driver.MongoBulkWriteException`1[MongoDB.Bson.BsonDocument]
A bulk write operation resulted in one or more errors.
  E11000 duplicate key error collection: FxTask.hangfire.jobGraph index: Key dup key: { Key: "stats:succeeded:2020-03-12" }
   at MongoDB.Driver.MongoCollectionImpl`1.BulkWrite(IClientSessionHandle session, IEnumerable`1 requests, BulkWriteOptions options, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.<>c__DisplayClass23_0.<BulkWrite>b__0(IClientSessionHandle session)
   at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSession[TResult](Func`2 func, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.BulkWrite(IEnumerable`1 requests, BulkWriteOptions options, CancellationToken cancellationToken)
   at Hangfire.Mongo.MongoWriteOnlyTransaction.Commit()
   at Hangfire.States.BackgroundJobStateChanger.ChangeState(StateChangeContext context)
   at Hangfire.Server.Worker.TryChangeState(BackgroundProcessContext context, IStorageConnection connection, IFetchedJob fetchedJob, IState state, String[] expectedStates, CancellationToken initializeToken, CancellationToken abortToken)

**Comment by gottscj** [comment]
@cnkker,

Could you elaborate a little bit?
What version are you using, how frequent do you see this error etc. Give me something to work with.

**Comment by gottscj** [comment]
closing due to inactivity
