### ISSUE TITLE
Error observing 'hangfire.notifications' for MongoDB as storage

### ISSUE THREAD

**Issue by rajurh** [sergeyzwezdin/Hangfire.Mongo#233]
Hi Team,

I am using Hangfire with .NET core and Mongo as a storage. We have continuous running job every 2 mins and with other different frequencies. From past 2 days application was running absolutely fine and today still Jobs are running correctly but in database we started seeing logs related to hangfire.notifications. When we started investigating found its capped collection with max value 100000 and I could see the data in the collection is reached max value 100000. Due to which I am suspecting getting error logs in application as shown below.

It will be good to know what is the best way to handle this situation? Also removing cap doesnt help because the volume keep growing which is not ideal in production scenario. TTL is not recommended solution because it doesn't work on capped collection (FYI)

Quick response will be much appreciated 

`Error observing 'hangfire.notifications'
MongoDB.Driver.MongoConnectionException: An exception occurred while receiving a message from the server.
 ---> System.IO.EndOfStreamException: Attempted to read past the end of the stream.
   at MongoDB.Driver.Core.Misc.StreamExtensionMethods.ReadBytes(Stream stream, Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Connections.BinaryConnection.ReceiveBuffer()
   --- End of inner exception stack trace ---
   at MongoDB.Driver.Core.Connections.BinaryConnection.ReceiveBuffer()
   at MongoDB.Driver.Core.Connections.BinaryConnection.ReceiveBuffer(Int32 responseTo, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Connections.BinaryConnection.ReceiveMessage(Int32 responseTo, IMessageEncoderSelector encoderSelector, MessageEncoderSettings messageEncoderSettings, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.ConnectionPools.ExclusiveConnectionPool.AcquiredConnection.ReceiveMessage(Int32 responseTo, IMessageEncoderSelector encoderSelector, MessageEncoderSettings messageEncoderSettings, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1.Execute(IConnection connection, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.WireProtocol.CommandWireProtocol`1.Execute(IConnection connection, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.Server.ServerChannel.ExecuteProtocol[TResult](IWireProtocol`1 protocol, ICoreSession session, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.Server.ServerChannel.Command[TResult](ICoreSession session, ReadPreference readPreference, DatabaseNamespace databaseNamespace, BsonDocument command, IEnumerable`1 commandPayloads, IElementNameValidator commandValidator, BsonDocument additionalOptions, Action`1 postWriteAction, CommandResponseHandling responseHandling, IBsonSerializer`1 resultSerializer, MessageEncoderSettings messageEncoderSettings, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.AsyncCursor`1.ExecuteGetMoreCommand(IChannelHandle channel, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.AsyncCursor`1.GetNextBatch(CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.AsyncCursor`1.MoveNext(CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.AsyncCursorEnumerator`1.MoveNext()
   at Hangfire.Mongo.MongoNotificationObserver.Execute(CancellationToken cancellationToken)`

**Comment by gottscj** [comment]
@rajurh,

capped collections have a fixed count of items, when it reached the limit it will override the oldest documents in the db. consider it as a circular buffer. so it should not run out of i items.
https://docs.mongodb.com/manual/core/capped-collections/

Could you elaborate a bit on what version you are a using and something about your setup in general?

Thanks!

**Comment by rajurh** [comment]
> @rajurh,
> 
> capped collections have a fixed count of items, when it reached the limit it will override the oldest documents in the db. consider it as a circular buffer. so it should not run out of i items.
> https://docs.mongodb.com/manual/core/capped-collections/
> 
> Could you elaborate a bit on what version you are a using and something about your setup in general?
> 
> Thanks!

I am using Hangfire.AspNetCore 1.7.9
Hangfire.Mongo 0.6.6 

We have hangfire job which runs different frequencies like every 2min, 10min, 15min where it fires and based on which some business operations it performs like calling database and placing msg in rabbitmq etc.

Yes I agree with capped collection explanation its only application logs with error as shown in original thread.

But still Job gets fired and does what is supposed to do. Only its Error logs make application noisy.

**Comment by gottscj** [comment]
@rajurh,

It seems it could be an issue with the mongo driver. Looking at the inner exception, it looks like the driver is trying to read too much data from the stream while receiving data.
The NoticationObserver will restart, and even if it stopped, jobs would still be fetched at the specified poll interval. so your jobs will be executed. but I can understand you would like to avoid the noise in your logs. do they happen frequent?

found this in mongo's jira
https://jira.mongodb.org/browse/CSHARP-2495

It seems that the network stream could perhaps be interrupted. Do you run i a local setup?

**Comment by rajurh** [comment]
@gottscj 

Yes Jobs are getting executed no issue, its the logs which are getting flooded almost every time job kick starts in my case job runs every 2mins. Which means error log found every 2min once.

Now what I did is dropped entire database and recreated it started working without any issues but this will not be a production solution. I am more concerned if issue occurs in Prod what are the options? And can hangfire handle this situation more gracefully?

I am running in AKS setup.

**Comment by gottscj** [comment]
@rajurh,

Its the MongoDB driver which throws the exception trying to read from the network stream. My guess is that there is an issue with the network or its a bug in the driver. I am catching the exception, so there is not much more I can do?

I will try to reproduce, but I dont think I can in a local setup. :)

**Comment by gottscj** [comment]
@rajurh,
I tried reproducing using the sample project in Hangfire.Mongo. I was not able to reproduce the error locally.

Did the error persist?
You might need to configure the MongoClient differently for running in AKS setup? 

![image](https://user-images.githubusercontent.com/12970565/80274464-d0112b00-86da-11ea-9afb-9ffe08cf5c63.png)

**Comment by gottscj** [comment]
@rajurh,

Im closing this due to inactivity, please let me know if you solved it.

thanks!

**Comment by rajurh** [comment]
> @rajurh,
> 
> Im closing this due to inactivity, please let me know if you solved it.
> 
> thanks!

@gottscj  - No still issue is observed but functionality is not disturbed its the noisy logs
