### ISSUE TITLE
Unhandled exception. MongoDB.Driver.MongoCommandException: Command delete failed: not authorized on DATABASE to execute command { delete: "hangfire.migrationLock"

### ISSUE THREAD

**Issue by juniormayhe** [sergeyzwezdin/Hangfire.Mongo#245]
Hello

does anyone know what would be the possible causes for this error while starting up a dotnet core application within a container? Locally it works fine.

Program.cs crashes on CreateHostBuilder(args).Build().Run(); and here are the docker logs:

```
[ERROR   ] Unhandled exception. MongoDB.Driver.MongoCommandException: Command delete failed: not authorized on MY_HANGFIRE_DATABASE to execute command { delete: "hangfire.migrationLock", ordered: true, deletes: [ { q: { _id: ObjectId('5c351d07197a9bcdba4832fc') }, limit: 1 } ] }.
[ERROR   ]    at MongoDB.Driver.Core.WireProtocol.CommandUsingQueryMessageWireProtocol`1.ProcessReply(ConnectionId connectionId, ReplyMessage`1 reply)
[ERROR   ]    at MongoDB.Driver.Core.WireProtocol.CommandUsingQueryMessageWireProtocol`1.Execute(IConnection connection, CancellationToken cancellationToken)
[ERROR   ]    at MongoDB.Driver.Core.WireProtocol.CommandWireProtocol`1.Execute(IConnection connection, CancellationToken cancellationToken)
[ERROR   ]    at MongoDB.Driver.Core.Servers.Server.ServerChannel.ExecuteProtocol[TResult](IWireProtocol`1 protocol, ICoreSession session, CancellationToken cancellationToken)
[ERROR   ]    at MongoDB.Driver.Core.Servers.Server.ServerChannel.Command[TResult](ICoreSession session, ReadPreference readPreference, DatabaseNamespace databaseNamespace, BsonDocument command, IEnumerable`1 commandPayloads, IElementNameValidator commandValidator, BsonDocument additionalOptions, Action`1 postWriteAction, CommandResponseHandling responseHandling, IBsonSerializer`1 resultSerializer, MessageEncoderSettings messageEncoderSettings, CancellationToken cancellationToken)
[ERROR   ]    at MongoDB.Driver.Core.Operations.RetryableWriteCommandOperationBase.ExecuteAttempt(RetryableWriteContext context, Int32 attempt, Nullable`1 transactionNumber, CancellationToken cancellationToken)
[ERROR   ]    at MongoDB.Driver.Core.Operations.RetryableWriteOperationExecutor.Execute[TResult](IRetryableWriteOperation`1 operation, RetryableWriteContext context, CancellationToken cancellationToken)
[ERROR   ]    at MongoDB.Driver.Core.Operations.BulkUnmixedWriteOperationBase`1.ExecuteBatch(RetryableWriteContext context, Batch batch, CancellationToken cancellationToken)
[ERROR   ]    at MongoDB.Driver.Core.Operations.BulkUnmixedWriteOperationBase`1.ExecuteBatches(RetryableWriteContext context, CancellationToken cancellationToken)
[ERROR   ]    at MongoDB.Driver.Core.Operations.BulkUnmixedWriteOperationBase`1.Execute(RetryableWriteContext context, CancellationToken cancellationToken)
[ERROR   ]    at MongoDB.Driver.Core.Operations.BulkMixedWriteOperation.ExecuteBatch(RetryableWriteContext context, Batch batch, CancellationToken cancellationToken)
[ERROR   ]    at MongoDB.Driver.Core.Operations.BulkMixedWriteOperation.Execute(IWriteBinding binding, CancellationToken cancellationToken)
[ERROR   ]    at MongoDB.Driver.OperationExecutor.ExecuteWriteOperation[TResult](IWriteBinding binding, IWriteOperation`1 operation, CancellationToken cancellationToken)
[ERROR   ]    at MongoDB.Driver.MongoCollectionImpl`1.ExecuteWriteOperation[TResult](IClientSessionHandle session, IWriteOperation`1 operation, CancellationToken cancellationToken)
[ERROR   ]    at MongoDB.Driver.MongoCollectionImpl`1.BulkWrite(IClientSessionHandle session, IEnumerable`1 requests, BulkWriteOptions options, CancellationToken cancellationToken)
[ERROR   ]    at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSession[TResult](Func`2 func, CancellationToken cancellationToken)
[ERROR   ]    at MongoDB.Driver.MongoCollectionImpl`1.BulkWrite(IEnumerable`1 requests, BulkWriteOptions options, CancellationToken cancellationToken)
[ERROR   ]    at MongoDB.Driver.MongoCollectionBase`1.DeleteOne(FilterDefinition`1 filter, DeleteOptions options, Func`2 bulkWrite)
[ERROR   ]    at MongoDB.Driver.MongoCollectionBase`1.DeleteOne(FilterDefinition`1 filter, DeleteOptions options, CancellationToken cancellationToken)
[ERROR   ]    at MongoDB.Driver.MongoCollectionBase`1.DeleteOne(FilterDefinition`1 filter, CancellationToken cancellationToken)
[ERROR   ]    at Hangfire.Mongo.Migration.MigrationLock.DeleteMigrationLock()
[ERROR   ]    at Hangfire.Mongo.Migration.MongoMigrationManager.MigrateIfNeeded(MongoStorageOptions storageOptions, IMongoDatabase database)
[ERROR   ]    at Hangfire.Mongo.MongoStorage..ctor(MongoClient mongoClient, String databaseName, MongoStorageOptions storageOptions)
[ERROR   ]    at Hangfire.Mongo.MongoBootstrapperConfigurationExtensions.UseMongoStorage(IGlobalConfiguration configuration, String connectionString, MongoStorageOptions storageOptions)
```

I guess it could be related to `Hangfire.Mongo.Migration.MigrationLock.DeleteMigrationLock()` method, but I am not aware of hangfire internals.

Could this be totally related to user permissions and MongoDB.Driver fails to execute the delete command?

Thanks

**Comment by juniormayhe** [comment]
It seems the problem was the connection string that was not properly set in our continuous integration. It must be something like

`mongodb://<mongo_user_name>:<password>@<host>/<database name>?replicaSet=<replica set name>`

**Comment by gottscj** [comment]
@juniormayhe,

thanks for updating the issue! Im glad you solved your issue.

**Comment by vishnutej9492** [comment]
Had this same issue and this was very helpful.

tried using this format and it would have this same error in containers
mongodb+srv://"username":"password"@"clusterURL"/"dbName"?retryWrites=true&w=majority

but switched to the legacy format of declaring the connection strings
mongodb://"username":"password"@"clusterURL-shard1","clusterURL-shard2","clusterURL-shard3"/"dbName"?ssl=true&replicaSet="replicaInfo"&authSource="authDb"&retryWrites=true&w=majority

and it works fine

Hangfire.mongo doesn't like new format mongo strings im guessing
