### ISSUE TITLE
Cannot use more than 64 queue

### ISSUE THREAD

**Issue by Muhammed-Aslan** [sergeyzwezdin/Hangfire.Mongo#264]
I got a "The number of WaitHandles must be less than or equal to 64" exception when I tried to add more than 64 queue

**Comment by gottscj** [comment]
@Muhammed-Aslan,

could you please elaborate on the issue and paste the full exception and possible some logs ?

thanks!

**Comment by Muhammed-Aslan** [comment]
the log :
2021-01-23 12:22:36 [INFO]  (Hangfire.BackgroundJobServer) Starting Hangfire Server using job storage: 'Connection string: mongodb://<username>:<password>@localhost:27017, database name: Mongo-Hangfire-Sample-NETCore, prefix: hangfire'
2021-01-23 12:22:36 [INFO]  (Hangfire.BackgroundJobServer) Using the following options for Mongo DB job storage:
2021-01-23 12:22:36 [INFO]  (Hangfire.BackgroundJobServer)     Prefix: hangfire.
2021-01-23 12:22:36 [INFO]  (Hangfire.BackgroundJobServer) Using the following options for Hangfire Server:
    Worker count: 20
    Listening queues: 'Q1', 'Q2', 'Q3', 'Q4', 'Q5', 'Q6', 'Q7', 'Q8', 'Q9', 'Q10', 'Q11', 'Q12', 'Q13', 'Q14', 'Q15', 'Q16', 'Q17', 'Q18', 'Q19', 'Q20', 'Q21', 'Q22', 'Q23', 'Q24', 'Q25', 'Q26', 'Q27', 'Q28', 'Q29', 'Q30', 'Q31', 'Q32', 'Q33', 'Q34', 'Q35', 'Q36', 'Q37', 'Q38', 'Q39', 'Q40', 'Q41', 'Q42', 'Q43', 'Q44', 'Q45', 'Q46', 'Q47', 'Q48', 'Q49', 'Q50', 'Q51', 'Q52', 'Q53', 'Q54', 'Q55', 'Q56', 'Q57', 'Q58', 'Q59', 'Q60', 'Q61', 'Q62', 'Q63', 'Q64', 'Q65', 'Q66', 'Q67', 'Q68', 'Q69', 'Q70', 'Q71', 'Q72', 'Q73', 'Q74', 'Q75', 'Q76', 'Q77', 'Q78', 'Q79', 'Q80', 'Q81', 'Q82', 'Q83', 'Q84', 'Q85', 'Q86', 'Q87', 'Q88', 'Q89', 'Q90', 'Q91', 'Q92', 'Q93', 'Q94', 'Q95', 'Q96', 'Q97', 'Q98', 'Q99', 'Q100'
    Shutdown timeout: 00:00:15
    Schedule polling interval: 00:00:15
2021-01-23 12:22:36 [INFO]  (Hangfire.Server.BackgroundServerProcess) Server desktop-nv5ohop:13660:2ab44f20 successfully announced in 26.0277 ms
2021-01-23 12:22:36 [INFO]  (Hangfire.Server.BackgroundServerProcess) Server desktop-nv5ohop:13660:2ab44f20 is starting the registered dispatchers: ServerWatchdog, ServerJobCancellationWatcher, MongoExpirationManager, MongoNotificationObserver, Worker, DelayedJobScheduler, RecurringJobScheduler...
2021-01-23 12:22:36 [INFO]  (Hangfire.Server.ServerWatchdog) 2 servers were removed due to timeout
2021-01-23 12:22:36 [INFO]  (Hangfire.Server.BackgroundServerProcess) Server desktop-nv5ohop:13660:2ab44f20 all the dispatchers started





the exception :

System.NotSupportedException
  HResult=0x80131515
  Message=The number of WaitHandles must be less than or equal to 64.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.WaitHandle.WaitMultiple(ReadOnlySpan`1 waitHandles, Boolean waitAll, Int32 millisecondsTimeout)
   at System.Threading.WaitHandle.WaitMultiple(WaitHandle[] waitHandles, Boolean waitAll, Int32 millisecondsTimeout)
   at System.Threading.WaitHandle.WaitAny(WaitHandle[] waitHandles, TimeSpan timeout)
   at Hangfire.Mongo.JobQueueSemaphore.WaitAny(String[] queues, CancellationToken cancellationToken, TimeSpan timeout, String& queue, Boolean& timedOut) in D:\github\Hangfire.Mongo\src\Hangfire.Mongo\JobQueueSemaphore.cs:line 52
   at Hangfire.Mongo.MongoJobFetcher.FetchNextJob(String[] queues, CancellationToken cancellationToken) in D:\github\Hangfire.Mongo\src\Hangfire.Mongo\MongoJobFetcher.cs:line 84
   at Hangfire.Mongo.MongoConnection.FetchNextJob(String[] queues, CancellationToken cancellationToken) in D:\github\Hangfire.Mongo\src\Hangfire.Mongo\MongoConnection.cs:line 66
   at Hangfire.Server.Worker.Execute(BackgroundProcessContext context)
   at Hangfire.Server.BackgroundProcessDispatcherBuilder.ExecuteProcess(Guid executionId, Object state)
   at Hangfire.Processing.BackgroundExecution.Run(Action`2 callback, Object state)

**Comment by gottscj** [comment]
@Muhammed-Aslan,

Thanks! I was not aware there was this limitation, I will see if I can make the number of waithandles more scalable
