### ISSUE TITLE
Hangfire works in distributed environment, Hangfire.Mongo doesnt let it?

### ISSUE THREAD

**Issue by bhushan-firake** [sergeyzwezdin/Hangfire.Mongo#283]
First of all, thanks for the awesome library!

Can anyone help us on this issue? Are there any workarounds to this?

**Background:**
We are using Hangfire.Mongo v0.7.19(though the same problem exists in next versions as well).

We have 3 servers connected to same MongoDB.

Server 0: Creates jobs - where BackgroundJobServer is not initialized i.e. they only create jobs and do not process it. 
Server 1 & Server 2:  Process background jobs and recurring jobs put in the mongoDb from Server 0.

 We use default MigrateMongoMigrationStrategy on startup on all 3 servers with 1min QueuePollInterval(this doesn't matter here I guess)

Occasionally, we have to restart servers due to deployments. We do this one by one, for instance, when we are deploying Server 1, Server 2 keeps processing the jobs and when we are deploying Server 2, Server 1 keeps processing jobs.

**Problem:**

When we are deploying any of the Server 1 and Server 2, the migration runs on that server(we don't know why it runs - because we are not upgrading Hangfire.Mongo versions or anything, we haven't peeped into Hangfire.Mongo code till now. But we are sure, we don't touch Hangfire database as we have MySQL as our storage database for the app).

While the migrations are running, the other server queries notifications collection ending up creating the collection without capping. It has following effects:

1. It disables notification observer as the collection is not capped
2. It makes the migration fail on the server where we are deploying. This is because - [Version17](https://github.com/sergeyzwezdin/Hangfire.Mongo/blob/master/src/Hangfire.Mongo/Migration/Steps/Version17/00_AddNotificationsCollection.cs) tries to create the collection which already exists(without notifications). Once the migrations fail, the server doesn't process the background jobs as it has not yet created the instance of BackgroundServer.
3. This makes Server count to 0 in the dashboard which doesn't recover.
4. No jobs are processed, as the existing data was deleted by migration and it failed to continue migrations after which we repopulate the jobs

**Repro:**

1. Create two console applications connecting to the same Mongo database.
2. Keep one console running by adding some jobs in it. Make sure to add jobs which keep processing continuously without any gaps so that we are able to create the notifications collection when it tries to read it.
3. Try running the other console app, one of the times, it will produce this exception.

**Conclusion:**
This concludes that Hangfire.Mongo is not stable in a distributed environments. This is due to the fact that migrations don't consider distributed environment.

**Possible Solution:**
While migrating to Version17,  you could catch the exception which shows that the collection already exists and [convert the collection to capped](https://docs.mongodb.com/manual/reference/command/convertToCapped/). Again, this is not recommended in the sharded environment(We don't have a shard, can't tell for others :)).

**Comment by gottscj** [comment]
@bhushan-firake,

Thank you for the thourough explanation. Im not sure why the other server would run a migration if its the same version and the db is shared between the nodes. This should not happen. 
Could you share the schema version in the "hangfire.schema" collection? 
The ["MigrationManager"](https://github.com/sergeyzwezdin/Hangfire.Mongo/blob/master/src/Hangfire.Mongo/Migration/MongoMigrationManager.cs) compares the code with the schema version found in DB.

You could also disable migration actively on two of the servers by setting the "ByPassMigration" flag to true in the options. But the MigrationManager does have a distributed lock which is used, so only one node runs migrations.

**Comment by gottscj** [comment]
Please also share the contents of the "hangfire.migrationLock" collection.

**Comment by bhushan-firake** [comment]
@gottscj 

I think you misunderstood.

The server on which we are deploying runs the migrations while the other server is trying to execute the recurring and scheduled jobs.

The problem is:

When we are deploying on the server, migration runs. In the meantime, the other server creates the notification collection(default Mongo functionality). This fails the migration with the following exception:

```
2021-07-01 03:09:49 [INFO]  (Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy) Executing migration for schema 'Version05'
2021-07-01 03:09:49 [INFO]  (Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy) Executed migration step: CreateJobIdIndex[0] in 105ms
2021-07-01 03:09:49 [INFO]  (Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy) Executing migration for schema 'Version06'
2021-07-01 03:09:49 [INFO]  (Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy) Executed migration step: StateDataCreateIndex[0] in 26ms
2021-07-01 03:09:49 [INFO]  (Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy) Executed migration step: JobMigration[1] in 14ms
2021-07-01 03:09:49 [INFO]  (Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy) Executed migration step: ScheduledJobMigration[2] in 3ms
2021-07-01 03:09:49 [INFO]  (Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy) Executed migration step: RecurringJobMigration[3] in 5ms
2021-07-01 03:09:49 [INFO]  (Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy) Executed migration step: EnqueuedJobMigration[4] in 6ms
2021-07-01 03:09:49 [INFO]  (Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy) Executed migration step: CountersMigration[5] in 3ms
2021-07-01 03:09:49 [INFO]  (Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy) Executed migration step: RemoveObsoleteCollections[99] in 29ms
2021-07-01 03:09:49 [INFO]  (Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy) Executing migration for schema 'Version07'
2021-07-01 03:09:49 [INFO]  (Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy) Executed migration step: StateDataRename[0] in 12ms
2021-07-01 03:09:49 [INFO]  (Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy) Executed migration step: EnqueuedJobMigration[1] in 3ms
2021-07-01 03:09:49 [INFO]  (Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy) Executing migration for schema 'Version08'
2021-07-01 03:09:49 [INFO]  (Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy) Executed migration step: PascalCaseRename[0] in 21ms
2021-07-01 03:09:49 [INFO]  (Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy) Executing migration for schema 'Version09'
2021-07-01 03:09:49 [INFO]  (Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy) Executed migration step: CreateSignalCollection[0] in 31ms
2021-07-01 03:09:49 [INFO]  (Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy) Executing migration for schema 'Version10'
2021-07-01 03:09:49 [INFO]  (Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy) Executed migration step: UpdateSchemaCollection[0] in 2ms
2021-07-01 03:09:49 [INFO]  (Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy) Executing migration for schema 'Version11'
2021-07-01 03:09:49 [INFO]  (Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy) Executed migration step: UseObjectIdForJob[0] in 3ms
2021-07-01 03:09:49 [INFO]  (Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy) Executing migration for schema 'Version12'
2021-07-01 03:09:49 [INFO]  (Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy) Executed migration step: CreateIndexes[0] in 178ms
2021-07-01 03:09:49 [INFO]  (Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy) Executing migration for schema 'Version13'
2021-07-01 03:09:49 [INFO]  (Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy) Executed migration step: CombineJobsStateDataAndJobQueue[0] in 52ms
2021-07-01 03:09:49 [INFO]  (Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy) Executed migration step: CreateIndexes[1] in 200ms
2021-07-01 03:09:49 [INFO]  (Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy) Executed migration step: SumCounters[2] in 24ms
2021-07-01 03:09:49 [INFO]  (Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy) Executed migration step: AddFieldsToHash[3] in 4ms
2021-07-01 03:09:50 [INFO]  (Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy) Executed migration step: RemoveObsoleteCollections[99] in 77ms
2021-07-01 03:09:50 [INFO]  (Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy) Executing migration for schema 'Version14'
2021-07-01 03:09:50 [INFO]  (Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy) Executed migration step: RemoveMergedHashDtos[0] in 1ms
2021-07-01 03:09:50 [INFO]  (Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy) Executed migration step: RemoveLegacyLocks[1] in 1ms
2021-07-01 03:09:50 [INFO]  (Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy) Executing migration for schema 'Version15'
2021-07-01 03:09:50 [INFO]  (Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy) Executed migration step: CreateUniqueLockIndex[0] in 15ms
2021-07-01 03:09:50 [INFO]  (Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy) Executed migration step: MakeServerDataEmbeddedDocument[1] in 7ms
2021-07-01 03:09:50 [INFO]  (Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy) Executed migration step: CreateCompositeKeys[2] in 4ms
2021-07-01 03:09:50 [INFO]  (Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy) Executed migration step: RemoveMergedCounters[3] in 6ms
2021-07-01 03:09:50 [INFO]  (Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy) Executed migration step: UpdateListDtoKeySchema[4] in 24ms
2021-07-01 03:09:50 [INFO]  (Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy) Executed migration step: UpdateIndexes[5] in 229ms
2021-07-01 03:09:50 [INFO]  (Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy) Executing migration for schema 'Version16'
2021-07-01 03:09:50 [INFO]  (Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy) Executed migration step: UpdateSetDtoKeyAndValueField[0] in 13ms
2021-07-01 03:09:50 [INFO]  (Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy) Executed migration step: RemoveObsoleteCollections[99] in 8ms
2021-07-01 03:09:50 [INFO]  (Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy) Executing migration for schema 'Version17'
Unhandled exception. Hangfire.Mongo.Migration.MongoMigrationException: Migration failed in Hangfire.Mongo.Migration.Steps.Version17.AddNotificationsCollection
 ---> MongoDB.Driver.MongoCommandException: Command create failed: Collection already exists. NS: hangfire.hangfire.notifications.
   at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1.ProcessResponse(ConnectionId connectionId, CommandMessage responseMessage)
   at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1.Execute(IConnection connection, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.WireProtocol.CommandWireProtocol`1.Execute(IConnection connection, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.Server.ServerChannel.ExecuteProtocol[TResult](IWireProtocol`1 protocol, ICoreSession session, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.Server.ServerChannel.Command[TResult](ICoreSession session, ReadPreference readPreference, DatabaseNamespace databaseNamespace, BsonDocument command, IEnumerable`1 commandPayloads, IElementNameValidator commandValidator, BsonDocument additionalOptions, Action`1 postWriteAction, CommandResponseHandling responseHandling, IBsonSerializer`1 resultSerializer, MessageEncoderSettings messageEncoderSettings, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.CommandOperationBase`1.ExecuteProtocol(IChannelHandle channel, ICoreSessionHandle session, ReadPreference readPreference, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.CommandOperationBase`1.ExecuteProtocol(IChannelSource channelSource, ICoreSessionHandle session, ReadPreference readPreference, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.WriteCommandOperation`1.Execute(IWriteBinding binding, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.CreateCollectionOperation.Execute(IWriteBinding binding, CancellationToken cancellationToken)
   at MongoDB.Driver.OperationExecutor.ExecuteWriteOperation[TResult](IWriteBinding binding, IWriteOperation`1 operation, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoDatabaseImpl.ExecuteWriteOperation[T](IClientSessionHandle session, IWriteOperation`1 operation, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoDatabaseImpl.CreateCollectionHelper[TDocument](IClientSessionHandle session, String name, CreateCollectionOptions`1 options, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoDatabaseImpl.CreateCollection(IClientSessionHandle session, String name, CreateCollectionOptions options, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoDatabaseImpl.<>c__DisplayClass21_0.<CreateCollection>b__0(IClientSessionHandle session)
   at MongoDB.Driver.MongoDatabaseImpl.UsingImplicitSession(Action`1 func, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoDatabaseImpl.CreateCollection(String name, CreateCollectionOptions options, CancellationToken cancellationToken)
   at Hangfire.Mongo.Migration.Steps.Version17.AddNotificationsCollection.Execute(IMongoDatabase database, MongoStorageOptions storageOptions, IMongoMigrationContext migrationContext)
   at Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy.ExecuteMigration(IMongoDatabase database, MongoSchema fromSchema, MongoSchema toSchema)
   --- End of inner exception stack trace ---
   at Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy.ExecuteMigration(IMongoDatabase database, MongoSchema fromSchema, MongoSchema toSchema)
   at Hangfire.Mongo.Migration.Strategies.DropMongoMigrationStrategy.ExecuteMigration(IMongoDatabase database, MongoSchema fromSchema, MongoSchema toSchema)
   at Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy.Execute(MongoStorageOptions storageOptions, IMongoDatabase database, MongoSchema fromSchema, MongoSchema toSchema)
   at Hangfire.Mongo.Migration.MongoMigrationManager.Migrate(MongoBackupStrategy backupStrategy, MongoMigrationStrategy migrationStrategy)
   at Hangfire.Mongo.Migration.MongoMigrationManager.MigrateIfNeeded(MongoStorageOptions storageOptions, IMongoDatabase database)
   at Hangfire.Mongo.MongoStorage..ctor(MongoClient mongoClient, String databaseName, MongoStorageOptions storageOptions)
   at Hangfire.Mongo.MongoStorage..ctor(MongoClientSettings mongoClientSettings, String databaseName, MongoStorageOptions storageOptions)
   at Hangfire.Mongo.MongoBootstrapperConfigurationExtensions.UseMongoStorage(IGlobalConfiguration configuration, MongoClientSettings mongoClientSettings, String databaseName, MongoStorageOptions storageOptions)
   at Hangfire.Mongo.MongoBootstrapperConfigurationExtensions.UseMongoStorage(IGlobalConfiguration configuration, String connectionString, MongoStorageOptions storageOptions)
```

When this happens, as expected the migration fails on the server on which we are deploying. The other server fails to process the jobs as the database is not complete.

In this state, only 3 collections remain in MongoDb

hangfire.jobGraph
hangfire.locks
hangfire.notifications


Before deployment, the contents of hangfire.schema are as below:


```
{
    "_id" : 18,
    "Identifier" : "2ae19f70-4b6a-4df7-b963-7cf4708b0c70"
}
```
hangfire.migrationLock collection is empty.

**Comment by gottscj** [comment]
@bhushan-firake,

the default migration strategy will throw an exception. so most likely you use "drop". I'll try to reproduce using your instructions.

**Comment by gottscj** [comment]
@bhushan-firake,

I cant reproduce. Is this setup matching your description?
https://gist.github.com/gottscj/914620ddd862e1fd6a35d96cd3613917

**Comment by gottscj** [comment]
@bhushan-firake,

I tried to reproduce using the code in the gist. I could not reproduce. Hangfire.Mongo should not run migrations if the code has the same schema as the DB. If it runs migrations it should only run migrations to the needed schema, looking at your print, it seems it runs all migrations, which seems off as the schema is version 18.
I recorded a small video.

https://user-images.githubusercontent.com/12970565/124888977-e735f300-dfd6-11eb-9a99-4377a25da5d2.mp4

**Comment by bhushan-firake** [comment]
@gottscj I will update you with my findings using your worker class.  

Can you share your nuget packet versions for Hangfire ?

**Comment by gottscj** [comment]
I used 0.7.19, same as your system. :)

**Comment by bhushan-firake** [comment]
@gottscj One of the app was dated previous version and the app was connecting every minute to get updates on a dashboard which triggered the migrations. 

Closing this issue, sorry for wasting your time.

**Comment by gottscj** [comment]
@bhushan-firake,

No worries. Im glad we figured it out! 
Thanks for letting me know!
