### ISSUE TITLE
Failed to change state to a 'Succeeded' one

### ISSUE THREAD

**Issue by axle-h** [sergeyzwezdin/Hangfire.Mongo#95]
Running a background job with the same name for the second time and we get: Failed to change state to a 'Succeeded' one due to an exception after 10 retry attempts

System.FormatException
Element 'key' does not match any field or property of class Hangfire.Mongo.Dto.ListDto.

System.FormatException: Element 'key' does not match any field or property of class Hangfire.Mongo.Dto.ListDto.
   at MongoDB.Bson.Serialization.BsonClassMapSerializer`1.DeserializeClass(BsonDeserializationContext context)
   at MongoDB.Bson.Serialization.BsonClassMapSerializer`1.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
   at MongoDB.Driver.OfTypeSerializer`2.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
   at MongoDB.Bson.Serialization.IBsonSerializerExtensions.Deserialize[TValue](IBsonSerializer`1 serializer, BsonDeserializationContext context)
   at MongoDB.Bson.Serialization.Serializers.ProjectingDeserializer`2.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
   at MongoDB.Bson.Serialization.IBsonSerializerExtensions.Deserialize[TValue](IBsonSerializer`1 serializer, BsonDeserializationContext context)
   at MongoDB.Driver.Core.Operations.CursorBatchDeserializationHelper.DeserializeBatch[TDocument](RawBsonArray batch, IBsonSerializer`1 documentSerializer, MessageEncoderSettings messageEncoderSettings)
   at MongoDB.Driver.Core.Operations.FindCommandOperation`1.CreateCursorBatch(BsonDocument commandResult)
   at MongoDB.Driver.Core.Operations.FindCommandOperation`1.CreateCursor(IChannelSourceHandle channelSource, BsonDocument commandResult, Boolean slaveOk)
   at MongoDB.Driver.Core.Operations.FindCommandOperation`1.Execute(IReadBinding binding, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.FindOperation`1.Execute(IReadBinding binding, CancellationToken cancellationToken)
   at MongoDB.Driver.OperationExecutor.ExecuteReadOperation[TResult](IReadBinding binding, IReadOperation`1 operation, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.ExecuteReadOperation[TResult](IReadOperation`1 operation, ReadPreference readPreference, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.ExecuteReadOperation[TResult](IReadOperation`1 operation, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.FindSync[TProjection](FilterDefinition`1 filter, FindOptions`2 options, CancellationToken cancellationToken)
   at MongoDB.Driver.FilteredMongoCollectionBase`1.FindSync[TProjection](FilterDefinition`1 filter, FindOptions`2 options, CancellationToken cancellationToken)
   at MongoDB.Driver.FindFluent`2.ToCursor(CancellationToken cancellationToken)
   at MongoDB.Driver.IAsyncCursorSourceExtensions.ToList[TDocument](IAsyncCursorSource`1 source, CancellationToken cancellationToken)
   at Hangfire.Mongo.MongoWriteOnlyTransaction.<>c__DisplayClass20_0.<TrimList>b__0(HangfireDbContext x)
   at Hangfire.Mongo.MongoWriteOnlyTransaction.Commit()
   at Hangfire.States.BackgroundJobStateChanger.ChangeState(StateChangeContext context, BackgroundJob backgroundJob, IState toState, String oldStateName)

**Comment by axle-h** [comment]
Looks to be a casing issue. Example document from the stateData collection:

   {
       "_id" : ObjectId("59a7d795f67fb164782a42e9"),
       "_t" : [ 
              "KeyValueDto", 
              "ExpiringKeyValueDto", 
              "ListDto"
          ],
          "Key" : "succeeded",
          "Value" : "59a7d785f67fb164782a42d4",
          "ExpireAt" : null
      }

**Comment by MarLoe** [comment]
Seems like the issue discussed in #51 
Please read through and see if the proposed solution applies to you.

**Comment by axle-h** [comment]
Interesting, thanks for that. I've added that JSON configuration and also applied the fix in #96 and I think it's fixed.
